column_width = 80

indent_width = 2
indent_type = "Spaces"

line_endings = "Unix"
quote_style = "AutoPreferDouble"

call_parentheses = "Always"
space_after_function_names = "Never"

collapse_simple_statement = "ConditionalOnly"

[sort_requires]
enabled = true
